name: glitters
description: A glittering widget for Flutter.
version: 0.1.1
homepage: https://github.com/kaboc/flutter_glitters

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
