name: glitters
description: A glittering widget for Flutter, handy for making part of your app a little shiny.
version: 0.1.4
homepage: https://github.com/kaboc/flutter_glitters

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
