name: glitters
description: A glittering widget for Flutter, handy for making some part of your app a little shiny.
version: 0.1.3
homepage: https://github.com/kaboc/flutter_glitters

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
